/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PassportRegistry } from './PassportRegistry.js';
export * as factories from './factories/index.js';
export { PassportRegistry__factory } from './factories/PassportRegistry__factory.js';