/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PassportRegistry {
      
    export type ManufacturerStruct = {walletAddress: AddressLike, approved: boolean, registeredAt: BigNumberish, name: string}

    export type ManufacturerStructOutput = [walletAddress: string, approved: boolean, registeredAt: bigint, name: string] & {walletAddress: string, approved: boolean, registeredAt: bigint, name: string }
  

    export type WarrantyStruct = {startTimestamp: BigNumberish, endTimestamp: BigNumberish}

    export type WarrantyStructOutput = [startTimestamp: bigint, endTimestamp: bigint] & {startTimestamp: bigint, endTimestamp: bigint }
  

    export type ProductStruct = {passportId: BigNumberish, manufacturer: AddressLike, currentOwner: AddressLike, status: BigNumberish, manufactureDate: BigNumberish, createdAt: BigNumberish, warranty: PassportRegistry.WarrantyStruct, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string}

    export type ProductStructOutput = [passportId: bigint, manufacturer: string, currentOwner: string, status: bigint, manufactureDate: bigint, createdAt: bigint, warranty: PassportRegistry.WarrantyStructOutput, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string] & {passportId: bigint, manufacturer: string, currentOwner: string, status: bigint, manufactureDate: bigint, createdAt: bigint, warranty: PassportRegistry.WarrantyStructOutput, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string }
  

    export type ServiceCenterStruct = {walletAddress: AddressLike, approved: boolean, registeredAt: BigNumberish, name: string}

    export type ServiceCenterStructOutput = [walletAddress: string, approved: boolean, registeredAt: bigint, name: string] & {walletAddress: string, approved: boolean, registeredAt: bigint, name: string }
  
    }

  export interface PassportRegistryInterface extends Interface {
    getFunction(nameOrSignature: "MAX_BRAND_LENGTH" | "MAX_CATEGORY_LENGTH" | "MAX_MODEL_NUMBER_LENGTH" | "MAX_NAME_LENGTH" | "MAX_PRODUCT_NAME_LENGTH" | "MAX_SERIAL_NUMBER_LENGTH" | "addAdmin" | "getCurrentOwner" | "getManufacturer" | "getNextPassportId" | "getProduct" | "getProductStatus" | "getServiceCenter" | "isAdmin" | "isApprovedManufacturer" | "isApprovedServiceCenter" | "isWarrantyActive" | "passportExists" | "registerManufacturer" | "registerProduct" | "registerServiceCenter" | "revokeManufacturer" | "revokeServiceCenter"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminAdded" | "ManufacturerRegistered" | "ManufacturerRevoked" | "ProductRegistered" | "ServiceCenterRegistered" | "ServiceCenterRevoked"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_BRAND_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CATEGORY_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_MODEL_NUMBER_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PRODUCT_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SERIAL_NUMBER_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getCurrentOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getManufacturer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getNextPassportId', values?: undefined): string;
encodeFunctionData(functionFragment: 'getProduct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getServiceCenter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedManufacturer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedServiceCenter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isWarrantyActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'passportExists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerManufacturer', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'registerProduct', values: [AddressLike, string, string, string, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerServiceCenter', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'revokeManufacturer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeServiceCenter', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'MAX_BRAND_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CATEGORY_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_MODEL_NUMBER_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PRODUCT_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SERIAL_NUMBER_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNextPassportId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWarrantyActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passportExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeServiceCenter', data: BytesLike): Result;
  }

  
    export namespace AdminAddedEvent {
      export type InputTuple = [newAdmin: AddressLike, addedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [newAdmin: string, addedBy: string, timestamp: bigint];
      export interface OutputObject {newAdmin: string, addedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ManufacturerRegisteredEvent {
      export type InputTuple = [manufacturer: AddressLike, name: string, timestamp: BigNumberish];
      export type OutputTuple = [manufacturer: string, name: string, timestamp: bigint];
      export interface OutputObject {manufacturer: string, name: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ManufacturerRevokedEvent {
      export type InputTuple = [manufacturer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [manufacturer: string, timestamp: bigint];
      export interface OutputObject {manufacturer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductRegisteredEvent {
      export type InputTuple = [passportId: BigNumberish, manufacturer: AddressLike, initialOwner: AddressLike, serialNumber: string, productName: string, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, manufacturer: string, initialOwner: string, serialNumber: string, productName: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, manufacturer: string, initialOwner: string, serialNumber: string, productName: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceCenterRegisteredEvent {
      export type InputTuple = [serviceCenter: AddressLike, name: string, timestamp: BigNumberish];
      export type OutputTuple = [serviceCenter: string, name: string, timestamp: bigint];
      export interface OutputObject {serviceCenter: string, name: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceCenterRevokedEvent {
      export type InputTuple = [serviceCenter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [serviceCenter: string, timestamp: bigint];
      export interface OutputObject {serviceCenter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PassportRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): PassportRegistry;
    waitForDeployment(): Promise<this>;

    interface: PassportRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_BRAND_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_CATEGORY_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_MODEL_NUMBER_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PRODUCT_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SERIAL_NUMBER_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    addAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getCurrentOwner: TypedContractMethod<
      [passportId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getManufacturer: TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ManufacturerStructOutput],
      'view'
    >
    

    
    getNextPassportId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getProduct: TypedContractMethod<
      [passportId: BigNumberish, ],
      [PassportRegistry.ProductStructOutput],
      'view'
    >
    

    
    getProductStatus: TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getServiceCenter: TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ServiceCenterStructOutput],
      'view'
    >
    

    
    isAdmin: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isApprovedManufacturer: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isApprovedServiceCenter: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isWarrantyActive: TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    passportExists: TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    registerManufacturer: TypedContractMethod<
      [manufacturer: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerProduct: TypedContractMethod<
      [initialOwner: AddressLike, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string, manufactureDate: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    registerServiceCenter: TypedContractMethod<
      [serviceCenter: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeManufacturer: TypedContractMethod<
      [manufacturer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeServiceCenter: TypedContractMethod<
      [serviceCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_BRAND_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CATEGORY_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_MODEL_NUMBER_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PRODUCT_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SERIAL_NUMBER_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCurrentOwner'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getManufacturer'): TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ManufacturerStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getNextPassportId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [PassportRegistry.ProductStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProductStatus'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getServiceCenter'): TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ServiceCenterStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isAdmin'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedManufacturer'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedServiceCenter'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isWarrantyActive'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'passportExists'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerManufacturer'): TypedContractMethod<
      [manufacturer: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerProduct'): TypedContractMethod<
      [initialOwner: AddressLike, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string, manufactureDate: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerServiceCenter'): TypedContractMethod<
      [serviceCenter: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeManufacturer'): TypedContractMethod<
      [manufacturer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeServiceCenter'): TypedContractMethod<
      [serviceCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AdminAdded'): TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
getEvent(key: 'ManufacturerRegistered'): TypedContractEvent<ManufacturerRegisteredEvent.InputTuple, ManufacturerRegisteredEvent.OutputTuple, ManufacturerRegisteredEvent.OutputObject>;
getEvent(key: 'ManufacturerRevoked'): TypedContractEvent<ManufacturerRevokedEvent.InputTuple, ManufacturerRevokedEvent.OutputTuple, ManufacturerRevokedEvent.OutputObject>;
getEvent(key: 'ProductRegistered'): TypedContractEvent<ProductRegisteredEvent.InputTuple, ProductRegisteredEvent.OutputTuple, ProductRegisteredEvent.OutputObject>;
getEvent(key: 'ServiceCenterRegistered'): TypedContractEvent<ServiceCenterRegisteredEvent.InputTuple, ServiceCenterRegisteredEvent.OutputTuple, ServiceCenterRegisteredEvent.OutputObject>;
getEvent(key: 'ServiceCenterRevoked'): TypedContractEvent<ServiceCenterRevokedEvent.InputTuple, ServiceCenterRevokedEvent.OutputTuple, ServiceCenterRevokedEvent.OutputObject>;

    filters: {
      
      'AdminAdded(address,address,uint256)': TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
      AdminAdded: TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
    

      'ManufacturerRegistered(address,string,uint256)': TypedContractEvent<ManufacturerRegisteredEvent.InputTuple, ManufacturerRegisteredEvent.OutputTuple, ManufacturerRegisteredEvent.OutputObject>;
      ManufacturerRegistered: TypedContractEvent<ManufacturerRegisteredEvent.InputTuple, ManufacturerRegisteredEvent.OutputTuple, ManufacturerRegisteredEvent.OutputObject>;
    

      'ManufacturerRevoked(address,uint256)': TypedContractEvent<ManufacturerRevokedEvent.InputTuple, ManufacturerRevokedEvent.OutputTuple, ManufacturerRevokedEvent.OutputObject>;
      ManufacturerRevoked: TypedContractEvent<ManufacturerRevokedEvent.InputTuple, ManufacturerRevokedEvent.OutputTuple, ManufacturerRevokedEvent.OutputObject>;
    

      'ProductRegistered(uint256,address,address,string,string,uint256)': TypedContractEvent<ProductRegisteredEvent.InputTuple, ProductRegisteredEvent.OutputTuple, ProductRegisteredEvent.OutputObject>;
      ProductRegistered: TypedContractEvent<ProductRegisteredEvent.InputTuple, ProductRegisteredEvent.OutputTuple, ProductRegisteredEvent.OutputObject>;
    

      'ServiceCenterRegistered(address,string,uint256)': TypedContractEvent<ServiceCenterRegisteredEvent.InputTuple, ServiceCenterRegisteredEvent.OutputTuple, ServiceCenterRegisteredEvent.OutputObject>;
      ServiceCenterRegistered: TypedContractEvent<ServiceCenterRegisteredEvent.InputTuple, ServiceCenterRegisteredEvent.OutputTuple, ServiceCenterRegisteredEvent.OutputObject>;
    

      'ServiceCenterRevoked(address,uint256)': TypedContractEvent<ServiceCenterRevokedEvent.InputTuple, ServiceCenterRevokedEvent.OutputTuple, ServiceCenterRevokedEvent.OutputObject>;
      ServiceCenterRevoked: TypedContractEvent<ServiceCenterRevokedEvent.InputTuple, ServiceCenterRevokedEvent.OutputTuple, ServiceCenterRevokedEvent.OutputObject>;
    
    };
  }