/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PassportRegistry {
      
    export type ManufacturerStruct = {walletAddress: AddressLike, approved: boolean, registeredAt: BigNumberish, name: string}

    export type ManufacturerStructOutput = [walletAddress: string, approved: boolean, registeredAt: bigint, name: string] & {walletAddress: string, approved: boolean, registeredAt: bigint, name: string }
  

    export type PendingTransferStruct = {to: AddressLike, requestedAt: BigNumberish, exists: boolean}

    export type PendingTransferStructOutput = [to: string, requestedAt: bigint, exists: boolean] & {to: string, requestedAt: bigint, exists: boolean }
  

    export type WarrantyStruct = {startTimestamp: BigNumberish, endTimestamp: BigNumberish}

    export type WarrantyStructOutput = [startTimestamp: bigint, endTimestamp: bigint] & {startTimestamp: bigint, endTimestamp: bigint }
  

    export type ProductStruct = {passportId: BigNumberish, manufacturer: AddressLike, currentOwner: AddressLike, status: BigNumberish, previousOperationalStatus: BigNumberish, currentServiceCenter: AddressLike, manufactureDate: BigNumberish, createdAt: BigNumberish, repairCount: BigNumberish, lastRepairTimestamp: BigNumberish, warranty: PassportRegistry.WarrantyStruct, pendingTransfer: PassportRegistry.PendingTransferStruct, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string}

    export type ProductStructOutput = [passportId: bigint, manufacturer: string, currentOwner: string, status: bigint, previousOperationalStatus: bigint, currentServiceCenter: string, manufactureDate: bigint, createdAt: bigint, repairCount: bigint, lastRepairTimestamp: bigint, warranty: PassportRegistry.WarrantyStructOutput, pendingTransfer: PassportRegistry.PendingTransferStructOutput, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string] & {passportId: bigint, manufacturer: string, currentOwner: string, status: bigint, previousOperationalStatus: bigint, currentServiceCenter: string, manufactureDate: bigint, createdAt: bigint, repairCount: bigint, lastRepairTimestamp: bigint, warranty: PassportRegistry.WarrantyStructOutput, pendingTransfer: PassportRegistry.PendingTransferStructOutput, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string }
  

    export type ServiceCenterStruct = {walletAddress: AddressLike, approved: boolean, registeredAt: BigNumberish, name: string}

    export type ServiceCenterStructOutput = [walletAddress: string, approved: boolean, registeredAt: bigint, name: string] & {walletAddress: string, approved: boolean, registeredAt: bigint, name: string }
  
    }

  export interface PassportRegistryInterface extends Interface {
    getFunction(nameOrSignature: "MAX_BRAND_LENGTH" | "MAX_CATEGORY_LENGTH" | "MAX_MODEL_NUMBER_LENGTH" | "MAX_NAME_LENGTH" | "MAX_PRODUCT_NAME_LENGTH" | "MAX_REPAIR_DESCRIPTION_LENGTH" | "MAX_SERIAL_NUMBER_LENGTH" | "acceptTransfer" | "addAdmin" | "cancelTransfer" | "completeService" | "getCurrentOwner" | "getLastRepairTimestamp" | "getManufacturer" | "getNextPassportId" | "getPendingTransfer" | "getProduct" | "getProductStatus" | "getRepairCount" | "getServiceCenter" | "hasPendingTransfer" | "initiateTransfer" | "isAdmin" | "isApprovedManufacturer" | "isApprovedServiceCenter" | "isUnderService" | "isWarrantyActive" | "passportExists" | "registerManufacturer" | "registerProduct" | "registerServiceCenter" | "revokeManufacturer" | "revokeServiceCenter" | "startService"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminAdded" | "ManufacturerRegistered" | "ManufacturerRevoked" | "OwnershipTransferAccepted" | "OwnershipTransferCancelled" | "OwnershipTransferRequested" | "ProductRegistered" | "RepairAdded" | "ServiceCenterRegistered" | "ServiceCenterRevoked" | "ServiceCompleted" | "ServiceStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_BRAND_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_CATEGORY_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_MODEL_NUMBER_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_PRODUCT_NAME_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_REPAIR_DESCRIPTION_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'MAX_SERIAL_NUMBER_LENGTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'completeService', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getCurrentOwner', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLastRepairTimestamp', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getManufacturer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getNextPassportId', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProduct', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getProductStatus', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getRepairCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getServiceCenter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'hasPendingTransfer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'initiateTransfer', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'isAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedManufacturer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isApprovedServiceCenter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isUnderService', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'isWarrantyActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'passportExists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerManufacturer', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'registerProduct', values: [AddressLike, string, string, string, string, string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'registerServiceCenter', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'revokeManufacturer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeServiceCenter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'startService', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MAX_BRAND_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_CATEGORY_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_MODEL_NUMBER_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_PRODUCT_NAME_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_REPAIR_DESCRIPTION_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MAX_SERIAL_NUMBER_LENGTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'completeService', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLastRepairTimestamp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNextPassportId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProductStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRepairCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasPendingTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initiateTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isApprovedServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isUnderService', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isWarrantyActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'passportExists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProduct', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeManufacturer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeServiceCenter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startService', data: BytesLike): Result;
  }

  
    export namespace AdminAddedEvent {
      export type InputTuple = [newAdmin: AddressLike, addedBy: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [newAdmin: string, addedBy: string, timestamp: bigint];
      export interface OutputObject {newAdmin: string, addedBy: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ManufacturerRegisteredEvent {
      export type InputTuple = [manufacturer: AddressLike, name: string, timestamp: BigNumberish];
      export type OutputTuple = [manufacturer: string, name: string, timestamp: bigint];
      export interface OutputObject {manufacturer: string, name: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ManufacturerRevokedEvent {
      export type InputTuple = [manufacturer: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [manufacturer: string, timestamp: bigint];
      export interface OutputObject {manufacturer: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferAcceptedEvent {
      export type InputTuple = [passportId: BigNumberish, from: AddressLike, to: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, from: string, to: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, from: string, to: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferCancelledEvent {
      export type InputTuple = [passportId: BigNumberish, from: AddressLike, to: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, from: string, to: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, from: string, to: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferRequestedEvent {
      export type InputTuple = [passportId: BigNumberish, from: AddressLike, to: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, from: string, to: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, from: string, to: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProductRegisteredEvent {
      export type InputTuple = [passportId: BigNumberish, manufacturer: AddressLike, initialOwner: AddressLike, serialNumber: string, productName: string, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, manufacturer: string, initialOwner: string, serialNumber: string, productName: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, manufacturer: string, initialOwner: string, serialNumber: string, productName: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RepairAddedEvent {
      export type InputTuple = [passportId: BigNumberish, serviceCenter: AddressLike, description: string, repairNumber: BigNumberish, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, serviceCenter: string, description: string, repairNumber: bigint, timestamp: bigint];
      export interface OutputObject {passportId: bigint, serviceCenter: string, description: string, repairNumber: bigint, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceCenterRegisteredEvent {
      export type InputTuple = [serviceCenter: AddressLike, name: string, timestamp: BigNumberish];
      export type OutputTuple = [serviceCenter: string, name: string, timestamp: bigint];
      export interface OutputObject {serviceCenter: string, name: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceCenterRevokedEvent {
      export type InputTuple = [serviceCenter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [serviceCenter: string, timestamp: bigint];
      export interface OutputObject {serviceCenter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceCompletedEvent {
      export type InputTuple = [passportId: BigNumberish, serviceCenter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, serviceCenter: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, serviceCenter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ServiceStartedEvent {
      export type InputTuple = [passportId: BigNumberish, serviceCenter: AddressLike, timestamp: BigNumberish];
      export type OutputTuple = [passportId: bigint, serviceCenter: string, timestamp: bigint];
      export interface OutputObject {passportId: bigint, serviceCenter: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PassportRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): PassportRegistry;
    waitForDeployment(): Promise<this>;

    interface: PassportRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_BRAND_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_CATEGORY_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_MODEL_NUMBER_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_PRODUCT_NAME_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_REPAIR_DESCRIPTION_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MAX_SERIAL_NUMBER_LENGTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptTransfer: TypedContractMethod<
      [passportId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    addAdmin: TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancelTransfer: TypedContractMethod<
      [passportId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    completeService: TypedContractMethod<
      [passportId: BigNumberish, description: string, ],
      [void],
      'nonpayable'
    >
    

    
    getCurrentOwner: TypedContractMethod<
      [passportId: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getLastRepairTimestamp: TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getManufacturer: TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ManufacturerStructOutput],
      'view'
    >
    

    
    getNextPassportId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getPendingTransfer: TypedContractMethod<
      [passportId: BigNumberish, ],
      [PassportRegistry.PendingTransferStructOutput],
      'view'
    >
    

    
    getProduct: TypedContractMethod<
      [passportId: BigNumberish, ],
      [PassportRegistry.ProductStructOutput],
      'view'
    >
    

    
    getProductStatus: TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getRepairCount: TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getServiceCenter: TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ServiceCenterStructOutput],
      'view'
    >
    

    
    hasPendingTransfer: TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    initiateTransfer: TypedContractMethod<
      [passportId: BigNumberish, recipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isAdmin: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isApprovedManufacturer: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isApprovedServiceCenter: TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isUnderService: TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    isWarrantyActive: TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    passportExists: TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    registerManufacturer: TypedContractMethod<
      [manufacturer: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >
    

    
    registerProduct: TypedContractMethod<
      [initialOwner: AddressLike, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string, manufactureDate: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    registerServiceCenter: TypedContractMethod<
      [serviceCenter: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >
    

    
    revokeManufacturer: TypedContractMethod<
      [manufacturer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeServiceCenter: TypedContractMethod<
      [serviceCenter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    startService: TypedContractMethod<
      [passportId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_BRAND_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_CATEGORY_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_MODEL_NUMBER_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_PRODUCT_NAME_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_REPAIR_DESCRIPTION_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MAX_SERIAL_NUMBER_LENGTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptTransfer'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [newAdmin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelTransfer'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'completeService'): TypedContractMethod<
      [passportId: BigNumberish, description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCurrentOwner'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getLastRepairTimestamp'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getManufacturer'): TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ManufacturerStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getNextPassportId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingTransfer'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [PassportRegistry.PendingTransferStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProduct'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [PassportRegistry.ProductStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getProductStatus'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRepairCount'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getServiceCenter'): TypedContractMethod<
      [account: AddressLike, ],
      [PassportRegistry.ServiceCenterStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hasPendingTransfer'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'initiateTransfer'): TypedContractMethod<
      [passportId: BigNumberish, recipient: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAdmin'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedManufacturer'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isApprovedServiceCenter'): TypedContractMethod<
      [account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isUnderService'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isWarrantyActive'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'passportExists'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerManufacturer'): TypedContractMethod<
      [manufacturer: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerProduct'): TypedContractMethod<
      [initialOwner: AddressLike, productName: string, brand: string, category: string, modelNumber: string, serialNumber: string, manufactureDate: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registerServiceCenter'): TypedContractMethod<
      [serviceCenter: AddressLike, name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeManufacturer'): TypedContractMethod<
      [manufacturer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeServiceCenter'): TypedContractMethod<
      [serviceCenter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startService'): TypedContractMethod<
      [passportId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AdminAdded'): TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
getEvent(key: 'ManufacturerRegistered'): TypedContractEvent<ManufacturerRegisteredEvent.InputTuple, ManufacturerRegisteredEvent.OutputTuple, ManufacturerRegisteredEvent.OutputObject>;
getEvent(key: 'ManufacturerRevoked'): TypedContractEvent<ManufacturerRevokedEvent.InputTuple, ManufacturerRevokedEvent.OutputTuple, ManufacturerRevokedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferAccepted'): TypedContractEvent<OwnershipTransferAcceptedEvent.InputTuple, OwnershipTransferAcceptedEvent.OutputTuple, OwnershipTransferAcceptedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferCancelled'): TypedContractEvent<OwnershipTransferCancelledEvent.InputTuple, OwnershipTransferCancelledEvent.OutputTuple, OwnershipTransferCancelledEvent.OutputObject>;
getEvent(key: 'OwnershipTransferRequested'): TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
getEvent(key: 'ProductRegistered'): TypedContractEvent<ProductRegisteredEvent.InputTuple, ProductRegisteredEvent.OutputTuple, ProductRegisteredEvent.OutputObject>;
getEvent(key: 'RepairAdded'): TypedContractEvent<RepairAddedEvent.InputTuple, RepairAddedEvent.OutputTuple, RepairAddedEvent.OutputObject>;
getEvent(key: 'ServiceCenterRegistered'): TypedContractEvent<ServiceCenterRegisteredEvent.InputTuple, ServiceCenterRegisteredEvent.OutputTuple, ServiceCenterRegisteredEvent.OutputObject>;
getEvent(key: 'ServiceCenterRevoked'): TypedContractEvent<ServiceCenterRevokedEvent.InputTuple, ServiceCenterRevokedEvent.OutputTuple, ServiceCenterRevokedEvent.OutputObject>;
getEvent(key: 'ServiceCompleted'): TypedContractEvent<ServiceCompletedEvent.InputTuple, ServiceCompletedEvent.OutputTuple, ServiceCompletedEvent.OutputObject>;
getEvent(key: 'ServiceStarted'): TypedContractEvent<ServiceStartedEvent.InputTuple, ServiceStartedEvent.OutputTuple, ServiceStartedEvent.OutputObject>;

    filters: {
      
      'AdminAdded(address,address,uint256)': TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
      AdminAdded: TypedContractEvent<AdminAddedEvent.InputTuple, AdminAddedEvent.OutputTuple, AdminAddedEvent.OutputObject>;
    

      'ManufacturerRegistered(address,string,uint256)': TypedContractEvent<ManufacturerRegisteredEvent.InputTuple, ManufacturerRegisteredEvent.OutputTuple, ManufacturerRegisteredEvent.OutputObject>;
      ManufacturerRegistered: TypedContractEvent<ManufacturerRegisteredEvent.InputTuple, ManufacturerRegisteredEvent.OutputTuple, ManufacturerRegisteredEvent.OutputObject>;
    

      'ManufacturerRevoked(address,uint256)': TypedContractEvent<ManufacturerRevokedEvent.InputTuple, ManufacturerRevokedEvent.OutputTuple, ManufacturerRevokedEvent.OutputObject>;
      ManufacturerRevoked: TypedContractEvent<ManufacturerRevokedEvent.InputTuple, ManufacturerRevokedEvent.OutputTuple, ManufacturerRevokedEvent.OutputObject>;
    

      'OwnershipTransferAccepted(uint256,address,address,uint256)': TypedContractEvent<OwnershipTransferAcceptedEvent.InputTuple, OwnershipTransferAcceptedEvent.OutputTuple, OwnershipTransferAcceptedEvent.OutputObject>;
      OwnershipTransferAccepted: TypedContractEvent<OwnershipTransferAcceptedEvent.InputTuple, OwnershipTransferAcceptedEvent.OutputTuple, OwnershipTransferAcceptedEvent.OutputObject>;
    

      'OwnershipTransferCancelled(uint256,address,address,uint256)': TypedContractEvent<OwnershipTransferCancelledEvent.InputTuple, OwnershipTransferCancelledEvent.OutputTuple, OwnershipTransferCancelledEvent.OutputObject>;
      OwnershipTransferCancelled: TypedContractEvent<OwnershipTransferCancelledEvent.InputTuple, OwnershipTransferCancelledEvent.OutputTuple, OwnershipTransferCancelledEvent.OutputObject>;
    

      'OwnershipTransferRequested(uint256,address,address,uint256)': TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
      OwnershipTransferRequested: TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
    

      'ProductRegistered(uint256,address,address,string,string,uint256)': TypedContractEvent<ProductRegisteredEvent.InputTuple, ProductRegisteredEvent.OutputTuple, ProductRegisteredEvent.OutputObject>;
      ProductRegistered: TypedContractEvent<ProductRegisteredEvent.InputTuple, ProductRegisteredEvent.OutputTuple, ProductRegisteredEvent.OutputObject>;
    

      'RepairAdded(uint256,address,string,uint256,uint256)': TypedContractEvent<RepairAddedEvent.InputTuple, RepairAddedEvent.OutputTuple, RepairAddedEvent.OutputObject>;
      RepairAdded: TypedContractEvent<RepairAddedEvent.InputTuple, RepairAddedEvent.OutputTuple, RepairAddedEvent.OutputObject>;
    

      'ServiceCenterRegistered(address,string,uint256)': TypedContractEvent<ServiceCenterRegisteredEvent.InputTuple, ServiceCenterRegisteredEvent.OutputTuple, ServiceCenterRegisteredEvent.OutputObject>;
      ServiceCenterRegistered: TypedContractEvent<ServiceCenterRegisteredEvent.InputTuple, ServiceCenterRegisteredEvent.OutputTuple, ServiceCenterRegisteredEvent.OutputObject>;
    

      'ServiceCenterRevoked(address,uint256)': TypedContractEvent<ServiceCenterRevokedEvent.InputTuple, ServiceCenterRevokedEvent.OutputTuple, ServiceCenterRevokedEvent.OutputObject>;
      ServiceCenterRevoked: TypedContractEvent<ServiceCenterRevokedEvent.InputTuple, ServiceCenterRevokedEvent.OutputTuple, ServiceCenterRevokedEvent.OutputObject>;
    

      'ServiceCompleted(uint256,address,uint256)': TypedContractEvent<ServiceCompletedEvent.InputTuple, ServiceCompletedEvent.OutputTuple, ServiceCompletedEvent.OutputObject>;
      ServiceCompleted: TypedContractEvent<ServiceCompletedEvent.InputTuple, ServiceCompletedEvent.OutputTuple, ServiceCompletedEvent.OutputObject>;
    

      'ServiceStarted(uint256,address,uint256)': TypedContractEvent<ServiceStartedEvent.InputTuple, ServiceStartedEvent.OutputTuple, ServiceStartedEvent.OutputObject>;
      ServiceStarted: TypedContractEvent<ServiceStartedEvent.InputTuple, ServiceStartedEvent.OutputTuple, ServiceStartedEvent.OutputObject>;
    
    };
  }